.github/workflows/ci.yml
discopop_explorer/PETGraphX.py
discopop_explorer/__init__.py
discopop_explorer/test/__init__.py
discopop_explorer/test/test_analyzer_end_to_end.py
discopop_explorer/test/test_pattern_detection.py

This commit
- Makes PETGraphX accessible for testing w/out passing XML,
- Moves present end-to-end tests to discopop_explorer/test/,
- Adds unit tests for do_all, reduction and pipeline detectors,
- Adds tests to CI.

Add unit tests for pattern detectors

---

.github/workflows/publish.yml
scripts/dev/create-release.sh

Until now, our "Publish Package" CI action did all the necessary steps for creating a new release when a new tag is pushed. This included creating a commit to update the version files, moving the tag to the new commit and then force-pushing. This interfered with the branch protection in our repository.
This pull request changes the workflow to create a new release by moving some of the steps to a shell script in order to not interfere with how we review pushes to protected branches.
The here-added script creates
- a commit "Release of Version ${VERSION}" in release/v${VERSION} to update the version files, and
- a tag "v${VERSION}" pointing to the new commit.
After that, it prints the steps that are required manually for finalizing the release creation.

Script to help creating a new DiscoPoP version

---

CMakeLists.txt

Creates a simple file in the discopop build directory with the following contents:
```
DP_BUILD=/home/lukas/git/discopop/build
DP_SOURCE=/home/lukas/git/discopop
LLVM_BIN_DIR=/usr/lib/llvm-11/bin
```

feature: save build configuration

---

discopop_explorer/__main__.py
discopop_wizard/classes/ExecutionConfiguration.py
discopop_wizard/classes/Suggestion.py
discopop_wizard/screens/execution.py
discopop_wizard/screens/main.py
discopop_wizard/screens/suggestions/overview.py
scripts/runDiscoPoP

- Store and Load execution configurations to / from JSON files
- Cleanup help strings of discopop_explorer and runDiscoPoP to follow a similar format
-  originally, the idea was to parse it automatically, has been discarded as this feature is not required at the moment.

Wizard: Save configuration to JSON and cleanup help strings

---

discopop_explorer/PETGraphX.py

This PR marks unused functions.
Marked functions can be ignored in the following analysis of sub-tree usages.

mark unused functions

---

discopop_wizard/classes/Settings.py

This PR improves the stability wrt. changing settings values.
Useful for example when jumping between branches or in the case of installing a newer version while keeping the old settings file.

stability improvements by loading default values for non existing settings

---

discopop_explorer/PETGraphX.py
discopop_explorer/generate_Data_CUInst.py
discopop_explorer/pattern_detection.py
discopop_explorer/pattern_detectors/do_all_detector.py
discopop_explorer/pattern_detectors/geometric_decomposition_detector.py
discopop_explorer/pattern_detectors/pipeline_detector.py
discopop_explorer/pattern_detectors/task_parallelism/filter.py
discopop_explorer/pattern_detectors/task_parallelism/preprocessor.py
discopop_explorer/pattern_detectors/task_parallelism/suggesters/data_sharing_clauses.py
discopop_explorer/pattern_detectors/task_parallelism/suggesters/dependency_clauses.py
discopop_explorer/pattern_detectors/task_parallelism/suggesters/tasks.py
discopop_explorer/pattern_detectors/task_parallelism/task_parallelism_detector.py
discopop_explorer/pattern_detectors/task_parallelism/tp_utils.py
discopop_explorer/plugins/pipeline.py
discopop_explorer/utils.py

Remove duplicate child/calls edge; Function CUs now know their children and vice versa, refactorings

---

DiscoPoP/DiscoPoP.cpp
DiscoPoP/DiscoPoP.hpp
discopop_explorer/PETGraphX.py
discopop_explorer/pattern_detectors/do_all_detector.py

This PR adds a check for performed FileIO operations and prevents such CUs from being parallelized in a do-all manner.
In the future, such CUs could be surrounded with critical regions.

Prevent do-all parallelization of FileIO

---

CMakeLists.txt

This PR prevents the generated `build/build_config.txt` from containing entries for prior builds.

clear build_config.txt before appending values

---

rtlib/iFunctions.cpp

Simplifies the detection of allocations which belong to addressed memory regions.
Old code commented out as it may become relevant in the future.
Required to properly handle reuse of memory addresses

memory profiling: check for most recent allocations first

---

discopop_wizard/wizard.py

Loading the window icon seems to be problematic on some systems.
This PR ensures that the application is still usable, even if loading the icon is not possible.

Minor GUI Stability improvement 

---

DiscoPoP/DiscoPoP.cpp

The removal of empty CUs can lead to broken successor graphs in some cases.
This PR allows empty CUs (such without instructions lines). Since no Dependencies will be mapped to those CUs, there should be no effect on the analysis results.

fix: do not remove empty CUs

---

discopop_wizard/screens/suggestions/overview.py

Adds a preview tab to show static and dynamic dependencies.
Before merge:
After merge:

gui: added preview for static and dynamic dependencies

---

discopop_explorer/parser.py

@goerlibe 
Hi,
this PR is required so that the exported PET Graph can be restored.
If the `frozen` property is crucial, please revert the change and let me know.
In the mean time, i will merge this PR.

fix: allow restoring of PET Graph via jsonpickle

---

discopop_explorer/PETGraphX.py

This issue prevented detection result objects from being restored from the dumped json file, if a non-empty basic block id was assigned to any node.

Fix(loading of dumped detection result): lxml.objectifiy.StringElement -> str

---

discopop_explorer/parser.py

mapping of functions without arguments to dummies not possible due to incorrect indentation.
Resulted in missing CALLSNODE edges in the PET graph.

fix(explorer): Mapping of dummy nodes to functions

---

docs/How_to_contribute.md
scripts/dev/check-commit-msg.py

The added hook validates the formatting of commit messages.

Commit msg hook

---

discopop_explorer/discopop_explorer.py
discopop_explorer/pattern_detectors/PatternInfo.py

Feature: assign unique ids to identified patterns

---

discopop_explorer/pattern_detectors/PatternInfo.py
discopop_explorer/utils.py
discopop_library/discopop_optimizer/PETParser/PETParser.py

However, this does not solve #435 but acts as an intermediate fix...

feat: added error handling to recursive workload calculation to make the analysis more robust for large codes.

---

scripts/CMakeLists.txt

- setup discopop_cc
- setup discopop_cxx
- setup discopop_cmake
during build.
Note: Setup of the following added to the Hotspot-Detection repository already:
- discopop_hotspot_cc
- discopop_hotspot_cxx
- discopop_hotspot_cmake

feat: create symlinks on cmake build
