discopop-project/discopop

discopop_explorer/PETGraphX.py, discopop_explorer/json_serializer.py, discopop_explorer/pattern_detectors/reduction_detector.py, discopop_explorer/test/test_pattern_detection.py, discopop_explorer/utils.py, discopop_explorer/variable.py, test/reduction.json
added reduction operator to the output
=> Reduction operation in output

discopop_explorer/generate_Data_CUInst.py, discopop_explorer/pattern_detectors/task_parallelism_detector.py
Contains a hotfix for erroneous default parameter handling for parameter "--llvm-cxxfilt-path".
Contains a bugfix for the generation of Data_CUInst.txt .
=> Task parallelism: Hotfix: Parameter error handling

discopop_explorer/pattern_detectors/task_parallelism_detector.py
Replaces the old, source code line based dependency validation for task parallelism with a PET Graph based validation.
=> PET based dependency validation

README.md, discopop_explorer/pattern_detectors/do_all_detector.py, discopop_explorer/pattern_detectors/geometric_decomposition_detector.py, discopop_explorer/pattern_detectors/pipeline_detector.py, discopop_explorer/pattern_detectors/reduction_detector.py, discopop_profiler/README.md, docs/DPGuide.md
=> cleanup: fix pipeline and documentation

docs/How_to_contribute.md
=> Added "how to contribute"

scripts/runDiscoPoP
Added a flag to specify arguments which are passed through to the DiscoPoP Explorer.
=> Execution Wizard: added --explorer-flags argument

DiscoPoP/DiscoPoP.cpp, DiscoPoP/DiscoPoP.hpp
=> 169 variable names not reported in cus

docs/Pattern_Detection/Patterns/Do-All.md, docs/Pattern_Detection/Patterns/Reduction.md
doc: fixed documentation for do-all pattern
=> doc: split documentation of do-all and reduction patterns

discopop_explorer/pattern_detectors/geometric_decomposition_detector.py, discopop_wizard/classes/ExecutionConfiguration.py, discopop_wizard/classes/Suggestions.py, discopop_wizard/screens/suggestions/overview.py, docs/Pattern_Detection/Patterns/Geometric_Decomposition.md
Adds the option to browse and display the created suggestions and show their targeted code sections in the original source code.
=> 192 discopop wizard show parallelization suggestions

DiscoPoP/DiscoPoP.cpp, discopop_explorer/utils.py
=> fix: classification of shared variables in discopop example

.github/workflows/ci.yml, CMakeLists.txt, discopop_wizard/assets/profiling_container/Dockerfile, discopop_wizard/wizard.py, docs/Manual_Quickstart/Manual_Setup.md
=> Wizard bugfixes

discopop_explorer/utils.py, discopop_explorer/variable.py
I often compare patterns.txt with older versions when testing, this will make finding different results much easier
=> chore(explorer): sort classified variables

discopop_explorer/PETGraphX.py
Adds the option to dump the created PET Graph to a gephi compatible format.
=> Dump pet to gephi

discopop_wizard/classes/Suggestion.py, discopop_wizard/screens/suggestions/overview.py
This PR makes the list of identified suggestions in the GUI scrollable using the existing scrollbar.
Support for mouse scrolling will be added in a future PR.
=> GUI: Scrollable Suggestions

discopop_wizard/screens/main.py
This PR makes the list of stored configurations scrollable
=> GUI: Scrollable Configuration

discopop_explorer/PETGraphX.py, discopop_explorer/generate_Data_CUInst.py, discopop_explorer/pattern_detectors/PatternInfo.py, discopop_explorer/pattern_detectors/task_parallelism/suggesters/barriers.py, discopop_explorer/pattern_detectors/task_parallelism/suggesters/dependency_clauses.py, discopop_explorer/pattern_detectors/task_parallelism/suggesters/tasks.py, discopop_explorer/pattern_detectors/task_parallelism/tp_utils.py
This PR adds implements stronger typing requirements for the LineID and NodeID as well as a run-time check for correct formatting of their stored values.
=> Feature/sophisticated type aliases for NodeID and LineID

discopop_library/CodeGenerator/CodeGenerator.py, discopop_library/CodeGenerator/classes/ContentBuffer.py, discopop_library/CodeGenerator/classes/Enums.py, discopop_library/CodeGenerator/classes/Line.py, discopop_library/CodeGenerator/classes/Pragma.py, discopop_library/CodeGenerator/classes/UnpackedSuggestion.py, discopop_library/requirements.txt
This PR:
- initialized the discopop_library
- adds a basic code generator using a simple interface for inserting suggestions into original source code.
Note:
`CodeGenerator/CodeGenerator.py :: from_pattern_info(..)` has not been tested yet.
=> Feature: discopop library - Basic Code Generator

DiscoPoP/DiscoPoP.cpp, rtlib/loop_counter.cpp
This PR re-enables the dynamic loop counting.
=> Dynamic loop counting

discopop_explorer/utils.py
```
int i;
for(i=0; i<10;i++)
...
foo(i);
```
should classify i as lastprivate
=> Fix var classification

CMakeLists.txt, discopop_library/CodeGenerator/CodeGenerator.py, discopop_library/CodeGenerator/classes/ContentBuffer.py
- Adds a rudimentary check for compilability to the code_generator
=> Feature/library/code generator/check compilability

discopop_explorer/PETGraphX.py
Unused duplicate of `utils.py:is_first_written()`.
=> Removal of dead duplicated code

discopop_explorer/PETGraphX.py, discopop_explorer/utils.py
- adds de-aliasing to incorporate knowledge from within called functions while reporting known variables
=> task classification: improved results by de-aliasing

discopop_wizard/screens/main.py, discopop_wizard/screens/suggestions/overview.py, discopop_wizard/utils.py, discopop_wizard/wizard.py
#326
hopefully this works, we have no macOS device to try it right now.
=> Fix tkinter issues on macOS

rtlib/CMakeLists.txt, rtlib/simple-alias-detection/CMakeLists.txt, rtlib/simple-alias-detection/compile.sh
adds the missing compile script as specified in #341
=> fix: add missing compile script

DiscoPoP/DiscoPoP.cpp, DiscoPoP/DiscoPoP.hpp, DiscoPoP/InstructionDG.cpp, DiscoPoP/InstructionDG.hpp, discopop_explorer/PETGraphX.py, discopop_explorer/__init__.py, discopop_explorer/parser.py, discopop_explorer/pattern_detection.py
This PR adds support for the hybrid dependency profiling.
@goerlibe
Since this is a rather large change, please check before approving.
=> Hybrid dependency profiling

.github/workflows/ci.yml, DiscoPoP/DiscoPoP.cpp, DiscoPoP/DiscoPoP.hpp, MANIFEST.in, discopop_library/FileMapping/FileMapping.py, setup.py
I hope the changes in setup.py don't break anything -  should we add more files to `package_data`?
~I did not yet verify that using `pathlib.Path` works with the CodeGenerator.~ --> seems to be ok
=> public library typing, load_file_mapping uses Path type

discopop_library/CodeGenerator/classes/ContentBuffer.py
=> fix(codegen): remove temporary object file

DiscoPoP/DiscoPoP.cpp, DiscoPoP/DiscoPoP.hpp
Hi, as a result of this PR, memory regions size for allocations using the Polybench xmalloc function will be reported as well.
=> feat(allocation_profiling): added support for posix_memalign

discopop_library/CodeGenerator/CodeGenerator.py, discopop_library/CodeGenerator/classes/ContentBuffer.py
optionally pass the compiler name to codegen instead of defaulting to `clang`
=> Codegen cc

discopop_library/discopop_optimizer/classes/context/ContextObjectUtils.py, discopop_library/discopop_optimizer/classes/system/System.py, discopop_library/discopop_optimizer/classes/system/system_utils.py
compatibility fixes to support recent updates in the OpenMP Microbenchmark Suite
=> Fix/optimizer/improve accuracy/open mp microbench

discopop_library/ConfigProvider/__main__.py, discopop_library/ConfigProvider/config_provider.py
=> Some Fixes for the Config Provider

discopop_library/HostpotLoader/hostpot_loader.py
=> fix(library)[hotspot_loader]: add file check

discopop_library/ConfigProvider/ConfigProviderArguments.py, discopop_library/ConfigProvider/__main__.py, discopop_library/ConfigProvider/config_provider.py, discopop_library/PatchGenerator/__main__.py
related to #477
until we merge the tools, the config_provider can now print the version string.
=> Config provider: print version

CMakeLists.txt, rtlib/CMakeLists.txt
=> Replace C++11 with C++17
